// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnkwXUYiyOfoR-AXxi7eS_uzkemSMw0IE',
    appId: '1:883189481280:web:cac7ad25b66133126c04a5',
    messagingSenderId: '883189481280',
    projectId: 'fir-project-d43d0',
    authDomain: 'fir-project-d43d0.firebaseapp.com',
    storageBucket: 'fir-project-d43d0.appspot.com',
    measurementId: 'G-1F6WNQX11T',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnkwXUYiyOfoR-AXxi7eS_uzkemSMw0IE',
    appId: '1:883189481280:web:9965ad5e2d6b44c86c04a5',
    messagingSenderId: '883189481280',
    projectId: 'fir-project-d43d0',
    authDomain: 'fir-project-d43d0.firebaseapp.com',
    storageBucket: 'fir-project-d43d0.appspot.com',
    measurementId: 'G-W962EGRPZG',
  );
}
